package cg.creamgod.boarderless.domain.ai

import cg.creamgod.boarderless.data.remote.randomUuid
import cg.creamgod.boarderless.data.requireBoundedDraftJsonDepth
import cg.creamgod.boarderless.domain.history.*
import cg.creamgod.boarderless.domain.model.*
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.*

internal data class AiDiagramCapabilities(
    val shapes: Set<NodeShape>,
    val nodeColors: Set<String>,
    val groupColors: Set<String>,
    val selfLoops: Boolean = false,
)

internal data class AiDiagramToolCall(
    val requestId: String,
    val sessionId: String,
    val callId: String,
    val name: String,
    val arguments: String,
)

internal enum class AiDiagramToolStatus { Read, Proposed, Rejected }

internal enum class AiDiagramToolFailure { Scope, Closed, DuplicateCall, UnknownTool, Schema, Limit, Locked, Dependency, Unsupported, Internal }

internal data class AiDiagramToolResult(
    val callId: String?,
    val status: AiDiagramToolStatus,
    val data: JsonObject = JsonObject(emptyMap()),
    val failure: AiDiagramToolFailure? = null,
)

private class DraftRejected(
    val code: AiDiagramToolFailure,
) : IllegalArgumentException("AI diagram tool rejected")

@Serializable private data class EmptyArgs(
    val schema: Int = 1,
)

@Serializable private data class NodesArgs(
    val nodes: List<NodeArgs>,
)

@Serializable private data class NodeArgs(
    val id: String,
    val text: String,
    val x: Float,
    val y: Float,
    val width: Float,
    val height: Float,
    val shape: String,
    val color: String,
    val parent: String? = null,
)

@Serializable private data class GroupsArgs(
    val groups: List<GroupArgs>,
)

@Serializable private data class GroupArgs(
    val id: String,
    val title: String,
    val x: Float,
    val y: Float,
    val width: Float,
    val height: Float,
    val color: String,
    val parent: String? = null,
    val children: List<String> = emptyList(),
)

@Serializable private data class RelationsArgs(
    val relations: List<RelationArgs>,
)

@Serializable private data class RelationArgs(
    val id: String,
    val source: String,
    val target: String,
    val direction: String,
    val label: String? = null,
    val intent: String? = null,
)

@Serializable private data class UpdatesArgs(
    val nodes: List<UpdateArgs>,
)

@Serializable private data class UpdateArgs(
    val id: String,
    val text: String? = null,
    val color: String? = null,
    val shape: String? = null,
)

@Serializable private data class LayoutArgs(
    val nodes: List<LayoutNodeArgs>,
)

@Serializable private data class LayoutNodeArgs(
    val id: String,
    val x: Float,
    val y: Float,
    val width: Float,
    val height: Float,
    val rotation: Float = 0f,
)

/** Neutral complete-call executor. No provider, HTTP, persistence, ACL or live-canvas callbacks.
 * Caller supplies the actual supported capability subset and approved object scope. Local UUIDs
 * are generated by the APP; tools see logical references only. Each rejected call leaves the draft
 * and proposal unchanged, but consumes its call ID/budget. Close clears private context and draft.
 */
internal class AiDiagramDraft(
    private val requestId: String,
    private val sessionId: String,
    workspace: Workspace,
    approvedIds: Set<CanvasObjectId>,
    capabilities: AiDiagramCapabilities,
) {
    private val json =
        Json {
            encodeDefaults = true
            allowStructuredMapKeys = true
        }
    private val capabilities =
        capabilities.copy(
            shapes = capabilities.shapes.toSet(),
            nodeColors = capabilities.nodeColors.toSet(),
            groupColors = capabilities.groupColors.toSet(),
        )
    private var baseline: Workspace? = freeze(workspace)
    private var working: Workspace? = baseline
    private var approved = approvedIds.toSet()
    private var references = approved.sortedBy { it.value }.mapIndexed { i, id -> "N${i + 1}" to id }.toMap()
    private var relationReferences =
        baseline!!
            .relations.values
            .filter { it.sourceObjectId in approved && it.targetObjectId in approved }
            .sortedBy { it.id.value }
            .mapIndexed { i, edge -> "E${i + 1}" to edge.id }
            .toMap()
    private val calls = mutableSetOf<String>()
    private var items = emptyList<AiProposalItem>()
    private val proposalId = randomUuid()
    private var argumentBytes = 0L

    init {
        require(identifier(requestId) && identifier(sessionId))
        require(approved.size <= 128 && approved.all { it in workspace.objects })
        require(workspace.version in 0..9_007_199_254_738_991L && relationReferences.size <= 256)
        require(approved.all { workspace.objects.getValue(it).version in 1..9_007_199_254_738_991L })
        require(capabilities.shapes.isNotEmpty() && capabilities.nodeColors.isNotEmpty() && capabilities.groupColors.isNotEmpty())
        require((capabilities.nodeColors + capabilities.groupColors).all { it.matches(Regex("[A-Za-z0-9#_-]{1,64}")) })
        require(approvedGraph().toString().encodeToByteArray().size <= 256 * 1024)
    }

    private fun freeze(workspace: Workspace): Workspace {
        val raw = json.encodeToString(workspace)
        require(raw.encodeToByteArray().size <= 6 * 1024 * 1024)
        requireBoundedDraftJsonDepth(raw)
        return json.decodeFromString(raw)
    }

    private fun reject(code: AiDiagramToolFailure): Nothing = throw DraftRejected(code)

    private fun requireTool(
        value: Boolean,
        code: AiDiagramToolFailure = AiDiagramToolFailure.Schema,
    ) {
        if (!value) reject(code)
    }

    private fun identifier(value: String) = value.matches(Regex("[A-Za-z0-9_-]{1,128}"))

    private fun text(value: String) {
        requireTool(value.encodeToByteArray().size <= 64 * 1024, AiDiagramToolFailure.Limit)
    }

    private fun transform(
        x: Float,
        y: Float,
        width: Float,
        height: Float,
        rotation: Float = 0f,
    ): CanvasTransform {
        requireTool(listOf(x, y, width, height, rotation).all { it.isFinite() })
        requireTool(
            kotlin.math.abs(x) <= 1_000_000 && kotlin.math.abs(y) <= 1_000_000 && width in 1f..100_000f && height in 1f..100_000f &&
                kotlin.math.abs(rotation) <= 360f,
        )
        return CanvasTransform(Vec2(x, y), CanvasSize(width, height), rotation)
    }

    private fun objectFor(
        ref: String,
        map: Map<String, CanvasObjectId> = references,
    ): CanvasObject = working!!.objects[map[ref] ?: reject(AiDiagramToolFailure.Scope)] ?: reject(AiDiagramToolFailure.Dependency)

    private fun editable(
        node: CanvasObject,
        affectsDescendants: Boolean = false,
    ) {
        requireTool((node as? TextNode)?.vectorPath == null, AiDiagramToolFailure.Unsupported)
        var current: CanvasObject? = node
        val visited = mutableSetOf<CanvasObjectId>()
        while (current != null) {
            requireTool(visited.add(current.id), AiDiagramToolFailure.Dependency)
            requireTool(!working!!.aiSequenceProtected(current.id), AiDiagramToolFailure.Unsupported)
            requireTool(!current.locked, AiDiagramToolFailure.Locked)
            current = current.parentId?.let { working!!.objects[it] ?: reject(AiDiagramToolFailure.Dependency) }
        }
        if (node is GroupFrame && affectsDescendants) {
            // Moving/reparenting a group must not affect unapproved descendants.
            working!!.objects.values.forEach { child ->
                var parent = child.parentId
                val seen = mutableSetOf<CanvasObjectId>()
                while (parent != null && seen.add(parent)) {
                    if (parent == node.id) {
                        requireTool(!working!!.aiSequenceProtected(child.id), AiDiagramToolFailure.Unsupported)
                        requireTool(child.id in references.values && !child.locked, AiDiagramToolFailure.Scope)
                    }
                    parent = working!!.objects[parent]?.parentId
                }
            }
        }
    }

    private fun parent(
        ref: String?,
        map: Map<String, CanvasObjectId>,
    ): CanvasObjectId? =
        ref?.let {
            val id = map[it] ?: reject(AiDiagramToolFailure.Scope)
            val node = working!!.objects[id]
            // New groups in the same atomic create batch are checked by the domain reducer.
            if (node != null) {
                requireTool(node is GroupFrame, AiDiagramToolFailure.Dependency)
                editable(node)
            }
            id
        }

    private fun newReferences(ids: List<String>): Map<String, CanvasObjectId> {
        requireTool(ids.isNotEmpty() && ids.size <= 128 && ids.distinct().size == ids.size)
        requireTool(references.size - approved.size + ids.size <= 128, AiDiagramToolFailure.Limit)
        requireTool(ids.all { identifier(it) && it !in references && it !in relationReferences })
        return references + ids.associateWith { CanvasObjectId(randomUuid()) }
    }

    private fun <T> batch(
        values: List<T>,
        ids: (T) -> String,
    ) {
        requireTool(values.isNotEmpty() && values.size <= 128 && values.map(ids).distinct().size == values.size)
    }

    private fun approvedGraph(
        graph: Workspace = working!!,
        refs: Map<String, CanvasObjectId> = references,
        edges: Map<String, RelationId> = relationReferences,
    ): JsonObject =
        buildJsonObject {
            put(
                "objects",
                JsonArray(
                    refs.map { (ref, id) ->
                        val node = graph.objects.getValue(id)
                        buildJsonObject {
                            put("id", ref)
                            put("version", node.version)
                            put("locked", node.locked)
                            put("sequenceReadOnly", graph.aiSequenceProtected(node.id))
                            put(
                                "parent",
                                refs.entries
                                    .firstOrNull { it.value == node.parentId }
                                    ?.key
                                    ?.let(::JsonPrimitive) ?: JsonNull,
                            )
                            put("x", node.transform.position.x)
                            put("y", node.transform.position.y)
                            put("width", node.transform.size.width)
                            put("height", node.transform.size.height)
                            put("rotation", node.transform.rotationDegrees)
                            when (node) {
                                is TextNode -> {
                                    put("kind", "text")
                                    put("text", node.text)
                                    put(
                                        "shape",
                                        if (node.vectorPath ==
                                            null
                                        ) {
                                            node.shape.token
                                        } else {
                                            "custom-vector"
                                        },
                                    )
                                    put("color", node.colorToken)
                                }

                                is GroupFrame -> {
                                    put("kind", "group")
                                    put("text", node.title)
                                    put("color", node.colorToken)
                                }

                                is MediaNode -> {
                                    put("kind", "media")
                                    put("text", node.altText)
                                    put("mediaKind", node.mediaKind.token)
                                }
                            }
                        }
                    },
                ),
            )
            val byId = refs.entries.associate { it.value to it.key }
            put("sequenceContexts", aiSequenceContexts(graph, byId, edges.entries.associate { it.value to it.key }))
            put(
                "relations",
                JsonArray(
                    graph.relations.values.filter { it.sourceObjectId in byId && it.targetObjectId in byId }.map { relation ->
                        buildJsonObject {
                            put("id", edges.entries.single { it.value == relation.id }.key)
                            put("version", relation.version)
                            put("source", byId.getValue(relation.sourceObjectId))
                            put("target", byId.getValue(relation.targetObjectId))
                            put("direction", relation.direction.name)
                            put("label", relation.label?.let(::JsonPrimitive) ?: JsonNull)
                            put("intent", relation.intent?.let(::JsonPrimitive) ?: JsonNull)
                        }
                    },
                ),
            )
        }

    fun execute(call: AiDiagramToolCall): AiDiagramToolResult {
        val safeId = call.callId.takeIf(::identifier)

        fun failure(code: AiDiagramToolFailure) = AiDiagramToolResult(safeId, AiDiagramToolStatus.Rejected, failure = code)
        if (working == null) return failure(AiDiagramToolFailure.Closed)
        if (call.requestId != requestId || call.sessionId != sessionId) return failure(AiDiagramToolFailure.Scope)
        if (safeId == null) return failure(AiDiagramToolFailure.Schema)
        if (call.callId in calls) return failure(AiDiagramToolFailure.DuplicateCall)
        if (calls.size >= 64) return failure(AiDiagramToolFailure.Limit)
        calls.add(call.callId)
        val bytes = call.arguments.encodeToByteArray().size
        argumentBytes += bytes
        if (bytes > 64 * 1024 || argumentBytes > 1024 * 1024) return failure(AiDiagramToolFailure.Limit)
        return try {
            requireBoundedDraftJsonDepth(call.arguments)
            strictArguments(call.arguments)
            var nextReferences = references
            var nextRelations = relationReferences.toMap()
            val operation: WorkspaceOperation? =
                when (call.name) {
                    "list_diagram_capabilities" -> {
                        json.decodeFromString<EmptyArgs>(call.arguments).also { requireTool(it.schema == 1) }
                        return AiDiagramToolResult(
                            safeId,
                            AiDiagramToolStatus.Read,
                            buildJsonObject {
                                put("shapes", JsonArray(capabilities.shapes.map { JsonPrimitive(it.token) }))
                                put("nodeColors", JsonArray(capabilities.nodeColors.map(::JsonPrimitive)))
                                put("groupColors", JsonArray(capabilities.groupColors.map(::JsonPrimitive)))
                                put("selfLoops", capabilities.selfLoops)
                                put("sequenceDiagrams", false)
                                put("tools", JsonArray(ToolNames.map(::JsonPrimitive)))
                            },
                        )
                    }

                    "read_approved_graph", "validate_diagram" -> {
                        json.decodeFromString<EmptyArgs>(call.arguments).also { requireTool(it.schema == 1) }
                        val data =
                            if (call.name ==
                                "read_approved_graph"
                            ) {
                                approvedGraph()
                            } else {
                                buildJsonObject {
                                    put("valid", true)
                                    put("proposalItems", items.size)
                                    put("committed", false)
                                }
                            }
                        requireTool(data.toString().encodeToByteArray().size <= 256 * 1024, AiDiagramToolFailure.Limit)
                        return AiDiagramToolResult(safeId, AiDiagramToolStatus.Read, data)
                    }

                    "create_nodes" -> {
                        val nodes = json.decodeFromString<NodesArgs>(call.arguments).nodes
                        batch(nodes) { it.id }
                        nextReferences = newReferences(nodes.map { it.id })
                        CreateObjectsOperation(
                            randomUuid(),
                            nodes.map {
                                text(it.text)
                                requireTool(it.color in capabilities.nodeColors, AiDiagramToolFailure.Unsupported)
                                val shape = NodeShape.fromToken(it.shape) ?: reject(AiDiagramToolFailure.Unsupported)
                                requireTool(shape in capabilities.shapes, AiDiagramToolFailure.Unsupported)
                                TextNode(
                                    nextReferences.getValue(it.id),
                                    parentId = parent(it.parent, references),
                                    transform = transform(it.x, it.y, it.width, it.height),
                                    text = it.text,
                                    colorToken = it.color,
                                    shape = shape,
                                )
                            },
                        )
                    }

                    "create_groups" -> {
                        val groups = json.decodeFromString<GroupsArgs>(call.arguments).groups
                        batch(groups) { it.id }
                        nextReferences = newReferences(groups.map { it.id })
                        val create =
                            CreateObjectsOperation(
                                randomUuid(),
                                groups.map {
                                    text(it.title)
                                    requireTool(it.color in capabilities.groupColors, AiDiagramToolFailure.Unsupported)
                                    requireTool(it.children.size <= 128)
                                    GroupFrame(
                                        nextReferences.getValue(it.id),
                                        parentId = parent(it.parent, nextReferences),
                                        transform = transform(it.x, it.y, it.width, it.height),
                                        title = it.title,
                                        colorToken = it.color,
                                    )
                                },
                            )
                        val children = groups.flatMap { group -> group.children.map { it to group.id } }
                        requireTool(children.map { it.first }.distinct().size == children.size)
                        val changes =
                            children.map { (ref, group) ->
                                val id = nextReferences[ref] ?: reject(AiDiagramToolFailure.Scope)
                                val child =
                                    working!!.objects[id] ?: create.objects.firstOrNull { it.id == id }
                                        ?: reject(AiDiagramToolFailure.Dependency)
                                if (id in working!!.objects) editable(child, affectsDescendants = true)
                                ParentChange(child.id, child.version, child.parentId, nextReferences.getValue(group))
                            }
                        if (changes.isEmpty()) {
                            create
                        } else {
                            TransactionOperation(
                                randomUuid(),
                                listOf(create, ReparentObjectsOperation(randomUuid(), changes)),
                            )
                        }
                    }

                    "create_relations" -> {
                        val relations = json.decodeFromString<RelationsArgs>(call.arguments).relations
                        batch(relations) { it.id }
                        requireTool(nextRelations.size + relations.size <= 256, AiDiagramToolFailure.Limit)
                        requireTool(relations.all { identifier(it.id) && it.id !in relationReferences && it.id !in references })
                        val values =
                            relations.map {
                                val source = objectFor(it.source)
                                val target = objectFor(it.target)
                                editable(source)
                                editable(target)
                                requireTool(capabilities.selfLoops || source.id != target.id, AiDiagramToolFailure.Unsupported)
                                val direction =
                                    RelationDirection.entries.firstOrNull { d -> d.name == it.direction }
                                        ?: reject(AiDiagramToolFailure.Unsupported)
                                it.label?.let(::text)
                                it.intent?.let(::text)
                                Relation(
                                    RelationId(randomUuid()),
                                    sourceObjectId = source.id,
                                    targetObjectId = target.id,
                                    direction = direction,
                                    label = it.label,
                                    intent = it.intent,
                                )
                            }
                        nextRelations = nextRelations + relations.zip(values).associate { (args, edge) -> args.id to edge.id }
                        CreateRelationsOperation(randomUuid(), values)
                    }

                    "update_nodes" -> {
                        val updates = json.decodeFromString<UpdatesArgs>(call.arguments).nodes
                        batch(updates) { it.id }
                        val operations =
                            updates.flatMap {
                                val node = objectFor(it.id)
                                editable(node)
                                requireTool(node is TextNode, AiDiagramToolFailure.Unsupported)
                                node as TextNode
                                requireTool(it.text != null || it.color != null || it.shape != null)
                                val ops = mutableListOf<WorkspaceOperation>()
                                it.text?.let { value ->
                                    text(value)
                                    ops.add(EditTextOperation(randomUuid(), listOf(TextChange(node.id, node.version, node.text, value))))
                                }
                                if (it.color != null || it.shape != null) {
                                    val color = it.color ?: node.colorToken
                                    val shape =
                                        it.shape?.let { token -> NodeShape.fromToken(token) ?: reject(AiDiagramToolFailure.Unsupported) }
                                            ?: node.shape
                                    requireTool(
                                        color in capabilities.nodeColors && shape in capabilities.shapes,
                                        AiDiagramToolFailure.Unsupported,
                                    )
                                    val previous =
                                        TextNodeAttributes(node.zIndex, node.locked, node.colorToken, node.shape, node.vectorPath)
                                    ops.add(
                                        UpdateTextNodeAttributesOperation(
                                            randomUuid(),
                                            listOf(
                                                TextNodeAttributesChange(
                                                    node.id,
                                                    node.version + if (it.text == null) 0 else 1,
                                                    previous,
                                                    previous.copy(colorToken = color, shape = shape),
                                                ),
                                            ),
                                        ),
                                    )
                                }
                                ops
                            }
                        TransactionOperation(randomUuid(), operations)
                    }

                    "layout_nodes" -> {
                        val layout = json.decodeFromString<LayoutArgs>(call.arguments).nodes
                        batch(layout) { it.id }
                        TransformObjectsOperation(
                            randomUuid(),
                            layout.map {
                                val node = objectFor(it.id)
                                editable(node, affectsDescendants = true)
                                TransformChange(
                                    node.id,
                                    node.version,
                                    node.transform,
                                    transform(it.x, it.y, it.width, it.height, it.rotation),
                                )
                            },
                        )
                    }

                    else -> {
                        reject(AiDiagramToolFailure.UnknownTool)
                    }
                }
            requireTool(items.size < 32, AiDiagramToolFailure.Limit)
            val applied = operation!!.applyTo(working!!) as? OperationResult.Applied ?: reject(AiDiagramToolFailure.Dependency)
            requireTool(aiSequenceUnchanged(working!!, applied.workspace), AiDiagramToolFailure.Unsupported)
            requireTool(items.sumOf { operationSize(it.operation) } + operationSize(operation) <= 200, AiDiagramToolFailure.Limit)
            requireTool(
                approvedGraph(applied.workspace, nextReferences, nextRelations).toString().encodeToByteArray().size <= 256 * 1024,
                AiDiagramToolFailure.Limit,
            )
            val item = AiProposalItem(randomUuid(), call.name, "AI tool draft; requires user review", operation)
            working = applied.workspace
            references = nextReferences
            relationReferences = nextRelations.toMap()
            items = items + item
            AiDiagramToolResult(
                safeId,
                AiDiagramToolStatus.Proposed,
                buildJsonObject {
                    put("logicalIds", JsonArray((nextReferences.keys + nextRelations.keys).map(::JsonPrimitive)))
                    put("proposalItems", items.size)
                    put("committed", false)
                },
            )
        } catch (
            failure: DraftRejected,
        ) {
            failure(failure.code)
        } catch (
            _: IllegalArgumentException,
        ) {
            failure(AiDiagramToolFailure.Schema)
        } catch (_: Exception) {
            failure(AiDiagramToolFailure.Internal)
        }
    }

    private fun operationSize(operation: WorkspaceOperation): Int =
        when (operation) {
            is CreateObjectsOperation -> operation.objects.size
            is CreateRelationsOperation -> operation.relations.size
            is ReparentObjectsOperation -> operation.changes.size
            is EditTextOperation -> operation.changes.size
            is TransformObjectsOperation -> operation.changes.size
            is UpdateTextNodeAttributesOperation -> operation.changes.size
            is TransactionOperation -> operation.operations.sumOf(::operationSize)
            else -> reject(AiDiagramToolFailure.Unsupported)
        }

    /** Local UI mapping only; never include these UUID values in provider bodies or diagnostics. */
    fun localReferences(): Map<String, CanvasObjectId> = if (working == null) emptyMap() else references.toMap()

    fun proposal(): AiProposal? =
        if (working == null ||
            items.isEmpty()
        ) {
            null
        } else {
            AiProposal(proposalId, baseline!!.version, items.toList())
        }

    fun close() {
        baseline = null
        working = null
        approved = emptySet()
        references = emptyMap()
        relationReferences = emptyMap()
        items =
            emptyList()
        calls.clear()
    }

    /** Reject repeated keys, including escaped aliases, instead of parser last-value-wins. */
    private fun strictArguments(raw: String) {
        val parsed = json.parseToJsonElement(raw)
        requireTool(parsed is JsonObject)

        fun types(value: JsonElement) {
            when (value) {
                is JsonObject -> {
                    value.forEach { (name, field) ->
                        if (name in setOf("x", "y", "width", "height", "rotation", "schema")) {
                            requireTool(field is JsonPrimitive && !field.isString && field.floatOrNull?.isFinite() == true)
                        }
                        if (name in
                            setOf("id", "text", "title", "color", "shape", "parent", "source", "target", "direction", "label", "intent")
                        ) {
                            requireTool(field == JsonNull || field is JsonPrimitive && field.isString)
                        }
                        if (name == "children") requireTool(field is JsonArray && field.all { it is JsonPrimitive && it.isString })
                        types(field)
                    }
                }

                is JsonArray -> {
                    value.forEach(::types)
                }

                else -> {
                    Unit
                }
            }
        }
        types(parsed)

        data class Frame(
            val keys: MutableSet<String>?,
            var keyExpected: Boolean,
        )
        val stack = mutableListOf<Frame>()
        var i = 0
        while (i < raw.length) {
            when (raw[i]) {
                '{' -> {
                    stack.add(Frame(mutableSetOf(), true))
                }

                '[' -> {
                    stack.add(Frame(null, false))
                }

                '}', ']' -> {
                    stack.removeAt(stack.lastIndex)
                }

                ',' -> {
                    stack.last().let { if (it.keys != null) it.keyExpected = true }
                }

                '"' -> {
                    val start = i++
                    while (i < raw.length && raw[i] != '"') {
                        if (raw[i] == '\\') i++
                        i++
                    }
                    val frame = stack.last()
                    if (frame.keys != null && frame.keyExpected) {
                        requireTool(frame.keys.add(json.decodeFromString<String>(raw.substring(start, i + 1))))
                        frame.keyExpected = false
                    }
                }
            }
            i++
        }
    }

    companion object {
        val ToolNames =
            listOf(
                "list_diagram_capabilities",
                "read_approved_graph",
                "create_nodes",
                "create_groups",
                "create_relations",
                "update_nodes",
                "layout_nodes",
                "validate_diagram",
            )
    }
}
